### ISSUE TITLE
Create CRC Cards for Application

### ISSUE THREAD

**Issue by ColeDewis** [CMPUT301W24T01/noRAM#29]
Discuss together and work on CRC cards to plan out the major classes and actors in the application.

**Comment by WhoShotCupidd** [comment]
Im worken so hard

**Comment by ColeDewis** [comment]
These may be updated over time - however, the initial version for pt2 is now done.

**Comment by ColeDewis** [comment]
These may be updated over time - however, the initial version for pt2 is now done.
